#!/usr/bin/env bash

git submodule update --init --recursive
vim +PluginInstall +qall
dotfiles="tmux.conf vim vimrc zshrc"
dotdir=$HOME/.dotfiles
for dotfile in $dotfiles; do
    ln -shf "$dotdir/$dotfile" "$HOME/.$dotfile"
done

